const BASE_MAIN_URL = 'http://localhost:3001';
//const BASE_MAIN_URL = 'https://api.movies.bezprobeloff.nomoredomains.icu';
const BASE_IMAGE_URL = 'https://api.nomoreparties.co';
const BASE_MOVIES_URL = 'https://api.nomoreparties.co/beatfilm-movies';
const SHORT_DURATION = 40;
const DESKTOP_WIDTH = 1280;
const PAD_WIDTH = 768;
const MOBILE_WIDTH = 320;
const INITIAL_COUNT_MOVIES_DESKTOP = 12;
const INITIAL_COUNT_MOVIES_PAD = 8;
const INITIAL_COUNT_MOVIES_MOBILE = 5;
const COUNT_ADD_MOVIES_DESKTOP = 3;
const COUNT_ADD_MOVIES_PAD = 2;
const COUNT_ADD_MOVIES_MOBILE = 2;
const PATTERN_EMAIL = '([A-z0-9_.-]{1,})@([A-z0-9_.-]{1,}).([A-z]{2,8})';

export {
  BASE_MAIN_URL,
  BASE_IMAGE_URL,
  BASE_MOVIES_URL,
  SHORT_DURATION,
  DESKTOP_WIDTH,
  PAD_WIDTH,
  MOBILE_WIDTH,
  INITIAL_COUNT_MOVIES_DESKTOP,
  INITIAL_COUNT_MOVIES_PAD,
  INITIAL_COUNT_MOVIES_MOBILE,
  COUNT_ADD_MOVIES_DESKTOP,
  COUNT_ADD_MOVIES_PAD,
  COUNT_ADD_MOVIES_MOBILE,
  PATTERN_EMAIL,
};
